# This is a basic workflow to help you get started with Actions

name: tweet_scheduler

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # workflow_dispatch:
  schedule:
    - cron: '15 10,19 * * *'    

jobs:
  hadleyfreebot-post:
    runs-on: ubuntu-latest
    
    env:
      TWITTER_CONSUMER_API_KEY_HADLEYBOT: ${{ secrets.TWITTER_CONSUMER_API_KEY_HADLEYBOT }}
      TWITTER_CONSUMER_API_SECRET_HADLEYBOT: ${{ secrets.TWITTER_CONSUMER_API_SECRET_HADLEYBOT }}
      TWITTER_ACCESS_TOKEN_HADLEYBOT: ${{ secrets.TWITTER_ACCESS_TOKEN_HADLEYBOT }}
      TWITTER_ACCESS_TOKEN_SECRET_HADLEYBOT: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET_HADLEYBOT }}
    
    defaults:
      run:
        working-directory: Code
    
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - name: Install OS dependencies
        run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev

      - uses: r-lib/actions/setup-r@master # Set up R runtime
        with:
          r-version: 'release'

      - uses: actions/cache@v2 # Set up cache so packages won't be compiled everytime job is run
        with:
           path:  ${{ env.R_LIBS_USER }}
           key: ${{ runner.os }}-scriptname-${{ hashFiles('Code/hadley_bot_script.R') }}
           restore-keys: ${{ runner.os }}-scriptname-

      - name: Install packages
        shell: Rscript {0}
        run: |
          install.packages("rtweet", dependencies = TRUE)
          install.packages("readr", dependencies = TRUE)
          install.packages("glue", dependencies = TRUE)
          install.packages("here", dependencies = TRUE)

      # Run R script (only call Rscript as we set working directory above)
      - name: Create and post tweet
        run: Rscript "hadley_bot_script.R"

      #Commit updated files to repo
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Data/*
          git commit -am "GA updates rows tweeted dataset"
          git push origin main
